version: 2

models:
  - name: stg_tpch_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_tpch_customers')
              field: customer_id

  - name: stg_tpch_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_name
        tests:
          - not_null

  - name: stg_tpch_lineitem
    columns:
      - name: order_id
        tests:
          - not_null
      - name: part_id
        tests:
          - not_null

  - name: stg_tpcds_item
    columns:
      - name: item_id
        tests:
          - unique
          - not_null
      - name: category
        tests:
          - accepted_values:
              values: ['Sports','Home','Books','Electronics','Children','Women','Men']
